FROM python:3.10-slim
WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN apt-get update && apt-get install -y gcc g++ \
    && pip install uv \
    && pip install torch==2.3.1+cpu torchvision==0.18.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html \
    && uv sync && rm -rf /var/lib/apt/lists/*
COPY tg_bot ./tg_bot
CMD ["python", "-m", "tg_bot.run"]
